databases:
  - name: quintal-do-ze-db
    plan: free
    databaseName: quintal_do_ze
    user: quintal_user

services:
  - type: web
    name: quintal-do-ze-sistema
    runtime: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: quintal-do-ze-db
          property: connectionString
